# theme: minima
#remote_theme: pages-themes/leap-day@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0

plugins:
- jekyll-remote-theme

title: skillup
author: fedebassetti
description: "my github pages site"
